### ISSUE TITLE
Add to F-droid

### ISSUE THREAD

**Issue by KOLANICH** [GermainZ/ActivityForceNewTask#15]
Since the official repo doesn't support HTTPS I guess we need to see the builds in f-droid, which uses https.

**Comment by GermainZ** [comment]
Please feel free to submit it to F-Droid. Last time I checked, they didn't welcome Xposed modules due to some technical issues / concerns with bundling library JARs, and I currently don't have time to write and submit the build file F-Droid requires.

Also, let's please keep this issues tracker free of name calling. Thank you. :)

**Comment by GermainZ** [comment]
https://f-droid.org/en/packages/com.germainz.activityforcenewtask/

Thanks to @Rudloff for [adding it](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.germainz.activityforcenewtask.yml)
